# 服务器基本信息
Web:
  Host: "127.0.0.1"
  Port: 11520
  # 展示在网站的标题
  ServerName: "我的世界"
  # 服务器核心
  ImplementationName: "Bukkit"
  # 服务器版本
  ImplementationVersion: "1.19.2"
  # 用于展示的主页地址
  HomePageUrl: "https://example.com/"


# Yggdrasil服务配置
Yggdrasil:
  Host: "127.0.0.1"
  Port: 11521
  # 允许的皮肤站域名
  SkinDomains:
    - "example.com"
    - "example.org"
  # RSA 公钥文件路径
  RsaPublicKey: "id_rsa.pub"
  # RSA 私钥文件路径
  RsaPrivateKey: "id_rsa"

# 邮箱配置
Email:
    # 邮箱服务器地址
    Host: "smtp.example.com"
    # 邮箱服务器端口
    Port: 465
    # 邮箱用户名
    Username: ""
    # 邮箱密码
    Password: ""
    # 邮箱发件人
    From: ""

Debug: true
