# 服务器基本信息(除了Host和Port是web服务的启动地址之外 其他的信息不具备功能性 只是用于网站上的展示)
Web:
  Host: 0.0.0.0
  Port: 11520
  # 服务器名字（用于展示）
  ServerName: 外置登录服务器
  # 网站主页简介
  Description: 这是一个有趣的服务器！
  # 服务器核心（用于展示）
  ImplementationName: Bukkit
  # 服务器版本（用于展示）
  ImplementationVersion: 1.19.2
  # 网站地址（玩家访问的地址）
  HomePageUrl: http://127.0.0.1:11520
  # 展示在网站的认证服务器地址
  YagdrasilUrl: http://0.0.0.0:11521
  # 展示在网站的服务器地址
  ServerUrl: mc-game.example.cn


# Yggdrasil服务配置
Yggdrasil:
  Host: 0.0.0.0
  Port: 11521
  # 允许的皮肤站域名
  SkinDomains:
    - example.com
    - example.org
  # RSA 公钥文件路径
  RsaPublicKey: id_rsa.pub
  # RSA 私钥文件路径
  RsaPrivateKey: id_rsa

# 邮箱配置
Email:
    # 邮箱服务器地址
    Host: smtp.example.com
    # 邮箱服务器端口
    Port: 465
    # 邮箱用户名
    Username: IV@example.com
    # 邮箱密码
    Password: 123456
    # 邮箱发件人
    From: IV@example.com

# 实名认证API配置

Debug: false
